# Generated by Django 4.0.6 on 2022-09-14 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='이름')),
                ('description', models.CharField(default='', max_length=200, verbose_name='설명')),
                ('address', models.CharField(default='', max_length=100, verbose_name='판매지')),
                ('delivery_cost', models.IntegerField(default=0, verbose_name='배송비')),
                ('status', models.CharField(choices=[('ready', '판매준비중'), ('sale', '판매중'), ('soldout', '판매완료')], default='ready', max_length=20, verbose_name='판매상태')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100, verbose_name='판매단위')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('stock', models.IntegerField(default=0, verbose_name='재고')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='상품')),
            ],
        ),
    ]
