# Generated by Django 4.0.6 on 2022-09-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='결제금액')),
                ('method', models.CharField(choices=[('card', '신용카드'), ('credit', '현금'), ('point', '포인트'), ('kakaopay', '카카오페이')], max_length=100, verbose_name='결제방법')),
                ('status', models.CharField(choices=[('ready', '결제 대기중'), ('cancel', '결제 취소'), ('complete', '결제 완료')], max_length=100, verbose_name='결제상태')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='주문')),
            ],
        ),
    ]
