# Generated by Django 4.0.6 on 2022-09-14 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='배송지')),
                ('delivery_cost', models.IntegerField(default=0, verbose_name='배송비')),
                ('total_price', models.IntegerField(default=0, verbose_name='총 가격')),
                ('status', models.CharField(choices=[('ready', '주문대기중'), ('cancel', '주문취소'), ('order_complete', '주문완료 & 결제 대기중'), ('pay_complete', '결제완료 & 배송 중'), ('delivery_complete', '배송 완료')], default='ready', max_length=20, verbose_name='주문상태')),
            ],
        ),
        migrations.CreateModel(
            name='PriceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='주문')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.price', verbose_name='가격')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.ManyToManyField(through='order.PriceOrder', to='product.price', verbose_name='가격'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='주문자'),
        ),
    ]
